### ISSUE TITLE
push to upstream terraform repo

### ISSUE THREAD

**Issue by philips** [coreos/terraform-provider-ct#2]
Blockers:

- fuze is not the right name

**Comment by s-urbaniak** [comment]
It seems ignition configuration has been upstreamed already: https://github.com/hashicorp/terraform/blob/master/builtin/providers/ignition

https://www.terraform.io/docs/providers/ignition/r/user.html

**Comment by philips** [comment]
@bison can we shut down this repo then?

**Comment by bison** [comment]
@philips Seeing that there's now Ignition support actually encourages me to figure out naming and try to get this upstream ASAP.

I think there's still room for using templated Fuze / CT YAML configs that are converted to Ignition over building configs with potentially dozens of individual resources.

**Comment by philips** [comment]
Can you outline some of those use cases?

**Comment by crawford** [comment]
This is exactly where terraform excels. You write a mostly environment-agnostic config and let terraform figure out the details of that particular environment. Container Linux Configs are designed to be treated the same way - the user writes one config for all of their environments. Terraform can then use CT to make the customizations needed.

For example, given the following Container Linux Config:

```yaml
etcd:
  version:                     "v3.0.15"
  advertise_client_urls:       "{public.IPv4}:2379"
  initial_advertise_peer_urls: "{private.IPv4}:2380"
  listen_client_urls:          "http://0.0.0.0:2379"
  listen_peer_urls:            "http://{private.IPv4}:2380"
  initial_cluster:             "%m=http://{private.IPv4}:2380"
```

CT will use `COREOS_DIGITALOCEAN_IPV4_PUBLIC_0` and `COREOS_DIGITALOCEAN_IPV4_PRIVATE_0` for `public.IPv4` and `private.IPv4` on DigitalOcean, respectively. On EC2 though, it uses `COREOS_EC2_IPV4_PUBLIC` and `COREOS_EC2_IPV4_LOCAL`.

If the config looked like the following (IPv6 vs IPv4):

```yaml
etcd:
  version:                     "v3.0.15"
  advertise_client_urls:       "{public.IPv6}:2379"
  initial_advertise_peer_urls: "{private.IPv6}:2380"
  listen_client_urls:          "http://0.0.0.0:2379"
  listen_peer_urls:            "http://{private.IPv6}:2380"
  initial_cluster:             "%m=http://{private.IPv6}:2380"
```

CT would similarly use `COREOS_DIGITALOCEAN_IPV6_PUBLIC_0` and `COREOS_DIGITALOCEAN_IPV6_PRIVATE_0` for DigitalOcean. If a user attempted to use this on EC2 though, terraform would fail, informing the user that we can't get IPv6 addresses on EC2.

By using Container Linux Configs instead of Ignition Configs, we can hide all of this complexity from the end user, yet still make it available to those who need it.
