### ISSUE TITLE
Add possibility to include local files

### ISSUE THREAD

**Issue by ae-v** [coreos/terraform-provider-ct#24]
Please add the possibility to set a files directory as a Terraform argument in order to include local files as in the ct cli tool.

**Comment by dghubble** [comment]
I don't see this making a lot of sense directly in the context of this provider. The plugin allows Terraform to parse Container Linux configs and render Ignition and Terraform has its own support for reading local files already. 

```
data "ct_config" "worker" {
  content      = "${file("worker.yaml")}"
  platform     = "ec2"
  pretty_print = false
}
```

`content` can be constructed from a file or using other providers (such as Terraform's `template_file`). If you're interested in combining multiple valid Container Linux configs, we're thinking of adding that feature in #22.

*This project might more appropriately have been called `terraform-provider-clc`.*

**Comment by ae-v** [comment]
Thanks for your feedback!

**Comment by danielgormly** [comment]
Does this not make sense? You can only import `.yaml` files to build the config righ? There are considerable benefits to using the appropriate file extension for the file and importing the contents from a parent yaml, the primary being:

- More flexible organisation of config files.
- Text editors using the proper context for hinting/linting etc.

**Comment by dghubble** [comment]
It does not. This provider plugin has no bearing on your ability to use files in Terraform. Please read my example and general Terraform docs like [file](https://www.terraform.io/docs/provisioners/file.html).

**Comment by bzub** [comment]
@dghubble I believe this issue is in regards to setting the `--files-dir` ct flag to allow using a config like:
```yaml
---
storage:
  files:
    - path: /opt/bin/myscript.sh
      filesystem: root
      mode: 0755
      contents:
        local: scripts/myscript.sh
```

Currently the above snippet results in an error from this provider:
```
local files require setting the --files-dir flag to the directory that contains the file
```

Personally I think it would be nice if `--files-dir` defaulted to terraform's `"${path.module}". Does this change the status of this issue?

**Comment by bzub** [comment]
@ae-v @danielgormly Here's how to accomplish using local files without the corresponding ct feature. Please note I'm using terraform v.0.12+ syntax which allows directly calling functions etc without enclosing them in `"${}"`.

example.tf
```hcl
data "ct_config" "base" {
  content = templatefile("${path.module}/ct.yaml",
    {
	my_script = indent(10, file("${path.module}/myscript.sh"))
    }
  )
}
```

ct.yaml
```yaml
storage:
  files:
    - path: /opt/bin/myscript.sh
      filesystem: root
      mode: 0755
      contents:
        inline: |
          ${my_script}
```

myscript.sh
```sh
#!/usr/bin/env sh

echo "My script!"
```
